config/routes.rb
ScandTest::Application.routes.draw do
  root :to  => 'employees#index'
  resources :employees
  match '/table' => 'employees#table'
  match 'employee/:id/edit' => 'employees#start_edit', :as => :employee_start_edit

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :date_of_birth, :first_name, :salary, :surname, :id

  validates :first_name,  :presence => true,
            :length => {:minimum => 2, :maximum => 15}

  validates :surname, :presence => true,
            :length => {:minimum => 2, :maximum => 15}

  validates :date_of_birth, :presence => true #,
  #:format => {:with => /^(19|20)\d\d[-\.] (0[1-9]|1[012])[-\.](0[1-9]|[12][0-9]|3[01])$/i}

  validates :salary,  :presence => true,
            :format => {:with => /[0-9]+/i}
			

	def self.to_csv 
		employees_headers = "First Name,Surname,Date of Birth,Salary".split(',')
		employees = Employee.all		
		csv_data = FasterCSV.generate do |csv| 
			csv << employees_headers
			employees.each do |emp| 
				csv << [emp.first_name, emp.surname, emp.date_of_birth,emp.salary]
			end 
		end 
		return csv_data
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index

  end

  def create
    new_employee = Employee.new(params[:employee])
    if new_employee.save
      respond_to do |format|
        format.html  { redirect_to :back}
        format.js
      end
    else
      redirect_to :back
    end
  end

  def new

  end

  def edit

  end

  def show

  end

  def update
    emp = Employee.find_by_id(params[:id])
    emp.first_name = params[:page][:first_name]
    emp.surname = params[:page][:surname]
    emp.date_of_birth = params[:page][:date_of_birth]
    emp.salary = params[:page][:salary]
    emp.save
    respond_to do |format|
      format.html  { redirect_to :back}
    end
	
  end

  def destroy
     Employee.find_by_id(params[:id]).delete
     respond_to do |format|
       format.html  { redirect_to :back}
       end
	   
  end

  def start_edit

  end

  def table
	respond_to do |format|
		format.html { render :json => Employee.all}
		format.csv { send_data Employee.to_csv, :type => 'text/csv; charset=iso-8859-1; header=present', :disposition => "attachment; filename=employees.csv"}
	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div id="employee_<%=h employee.id %>" onclick=<%= employee_start_edit_path(employee.id) %>>
  First Name: <span class="name"><%=h employee.first_name %></span>
  Surname: <span class="value"><%=h employee.surname %></span>
</div>

app/views/employees/_table.html.erb
<script type="text/JavaScript" src="index.js"></script>
<table name="Employees_table" id="employees" class="tablesorter" >
  <thead>
  <tr>
    <th id="FirstNameHeader">First_name</th>
    <th id="SurnameHeader">Surname</th>
    <th id="DateOfBirthHeader">Date of Birth</th>
    <th id="SalaryHeader">Salary</th>
  </tr>
  </thead>
  <tbody>
  <% Employee.all.each do |employee| %>
      <tr data-empid ="<%= employee.id %>">
        <td><%= employee.first_name %></td>
        <td><%= employee.surname %></td>
        <td><%= employee.date_of_birth%></td>
        <td><%= employee.salary %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/employees/create.js.erb
$('#opaco').toggleClass('hidden').removeAttr('style');
$('#popup').toggleClass('hidden');

refreshTable();

app/views/employees/index.erb
<ul >
  <% Employee.all.each do |employee| %>
      <li>
        <%= employee.first_name %> <%= employee.surname %> <%= employee.date_of_birth %> <%= employee.salary %>
      </li>
  <% end %>
</ul>

app/views/employees/index.html.erb
<script type="text/javascript" src="index.js"></script>
<div id="opaco" class="hidden"></div>
<div id="popup" class="hidden"></div>
<div id="elemets">
  <div id="employees_table">
    <%= render 'employees/table' %>
  </div>
  <button name ="Add_Button" id="AddButton"> Add </button>
  <button name ="Edit_Button" id="EditButton"> Edit </button>
  <button name = "Remove_Button" id="RemoveButton"> Remove </button>
  <%= link_to 'Download CSV', table_path(:format=>:csv) %>
</div>

<div id="popup_add" class="hidden">
  <div class="add" class="hidden">
    <h3>Add Employee</h3>
    <%= form_for Employee.new, :remote => true  do |f| %>
        <table>
          <tr>
            <td> First name:</td>
            <td><%= f.text_field :first_name %></td>
          </tr>
          <tr>
            <td> Surname:</td>
            <td><%= f.text_field :surname %></td>
          </tr>
          <tr>
            <td> Date of birth:</td>
            <td><%= f.text_field :date_of_birth %></td>
          </tr>
          <tr>
            <td> Salary:</td>
            <td><%= f.text_field :salary %></td>
          </tr>
        </table>
        <%= f.submit "Add" %>
        <input type="button" value="Cancel" class="CancelButton" onclick="closePopup();" />
    <% end %>
  </div>
</div>

<div id="popup_edit" class="hidden">
  <div class="edit" class="hidden">
    <h3>Edit Employee</h3>
    <table>
      <tr>
        <td> First name:</td>
        <td><input type="text" id="FirstNameText" /></td>
      </tr>
      <tr>
        <td> Surname:</td>
        <td><input type="text" id="SurnameText" /></td>
      </tr>
      <tr>
        <td> Date of birth:</td>
        <td><input type="text" id="DateOfBirthText" /></td>
      </tr>
      <tr>
        <td> Salary:</td>
        <td><input type="text" id="SalaryText" /></td>
      </tr>
    </table>
    <input type="button" value="Confirm" onclick="onConfirmButtonClick(); return false;" />
    <input type="button" value="Cancel" class="CancelButton" onclick="closePopup(); return false;" />
  </div>
</div>

app/views/employees/show.html.erb
<ul >
  <% Employee.all.each do |employee| %>
      <li>
        <%= employee.first_name %> <%= employee.surname %> <%= employee.date_of_birth %> <%= employee.salary %>
      </li>
  <% end %>
</ul>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script type="text/javascript" src="jquery.tablesorter.js"></script>
<script type="text/javascript" src="json_sans_eval.js"></script>
<![endif]-->
<%= stylesheet_link_tag "application", :media => "all" %>

<%= javascript_include_tag "application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scand Test Task</title>
  <%= render 'layouts/stylesheets' %>
  <%= csrf_meta_tags %>
</head>
<body onload = "onDocumentLoad();">

<%= yield %>

</body>
</html>